// What the palette says, in every language it says it in.
//
// Whole sentences rather than fragments joined at runtime: "Enable" + a name
// reads as English word order and comes out backwards in half the languages
// this could be translated into.

export const STRINGS = {
  en: {
    command: 'Command palette',
    shortcutsCommand: 'Change the shortcuts',
    shortcutsSubtitle: 'Bind the palette to whatever you like',
    shortcutsTitle: 'Shortcuts for the palette',
    shortcutsHint: 'Press a combination to add it. Anything Slack already uses is taken from it.',
    shortcutsSaved: 'Saved — {list}',
    recorderIdle: 'Click, then press a combination',
    recorderListening: 'Press it now… (Escape to give up)',
    recorderEmpty: 'None yet. Without one the palette falls back to Cmd/Ctrl+K.',
    remove: 'Remove',
    save: 'Save',
    cancel: 'Cancel',
    placeholder: 'Jump to a conversation, or type a command…',
    placeholderActions: 'Run an action…',
    placeholderPeople: 'Find someone…',
    placeholderChannels: 'Find a channel…',
    empty: 'Nothing matches.',
    searching: 'searching…',

    modeActions: 'Actions',
    modePeople: 'People',
    modeChannels: 'Channels',

    sectionChannels: 'Channels',
    sectionPeople: 'People',
    sectionGroups: 'Group messages',
    sectionActions: 'Actions',
    sectionMods: 'Your mods',
    sectionCatalogue: 'Catalogue',

    hintOpen: 'open',
    hintClose: 'close',
    channel: 'Channel',
    directMessage: 'Direct message',
    groupMessage: 'Group',

    openPanel: 'Open BetterSlack',
    browseThemes: 'Browse themes',
    browsePlugins: 'Browse plugins',
    customCss: 'Edit custom CSS',

    theme: 'Theme',
    plugin: 'Plugin',
    enableMod: 'Enable {name}',
    disableMod: 'Disable {name}',
    configureMod: 'Configure {name}',
    installMod: 'Install {name}',
    settingsCount: '{count} setting(s)',
  },
  fr: {
    command: 'Palette de commandes',
    shortcutsCommand: 'Changer les raccourcis',
    shortcutsSubtitle: 'Associer la palette aux touches de votre choix',
    shortcutsTitle: 'Raccourcis de la palette',
    shortcutsHint: 'Appuyez sur une combinaison pour l’ajouter. Celles que Slack utilise déjà lui sont reprises.',
    shortcutsSaved: 'Enregistré — {list}',
    recorderIdle: 'Cliquez, puis appuyez sur une combinaison',
    recorderListening: 'Appuyez maintenant… (Échap pour renoncer)',
    recorderEmpty: 'Aucun pour l’instant. Sans raccourci, la palette revient à Cmd/Ctrl+K.',
    remove: 'Retirer',
    save: 'Enregistrer',
    cancel: 'Annuler',
    placeholder: 'Aller à une conversation, ou taper une commande…',
    placeholderActions: 'Lancer une action…',
    placeholderPeople: 'Trouver quelqu’un…',
    placeholderChannels: 'Trouver un canal…',
    empty: 'Aucun résultat.',
    searching: 'recherche en cours…',

    modeActions: 'Actions',
    modePeople: 'Personnes',
    modeChannels: 'Canaux',

    sectionChannels: 'Canaux',
    sectionPeople: 'Personnes',
    sectionGroups: 'Conversations de groupe',
    sectionActions: 'Actions',
    sectionMods: 'Vos mods',
    sectionCatalogue: 'Catalogue',

    hintOpen: 'ouvrir',
    hintClose: 'fermer',
    channel: 'Canal',
    directMessage: 'Message direct',
    groupMessage: 'Groupe',

    openPanel: 'Ouvrir BetterSlack',
    browseThemes: 'Parcourir les thèmes',
    browsePlugins: 'Parcourir les plugins',
    customCss: 'Modifier le CSS personnalisé',

    theme: 'Thème',
    plugin: 'Plugin',
    enableMod: 'Activer {name}',
    disableMod: 'Désactiver {name}',
    configureMod: 'Configurer {name}',
    installMod: 'Installer {name}',
    settingsCount: '{count} réglage(s)',
  },
};
