// Everything the builder says, in every language it says it in.
//
// English is required and is what a missing language or key falls back to.
// Apart from the code so a translator never has to read any of it.

export const STRINGS = {
  en: {
    open: 'Theme builder',
    openHint: 'Design a theme with the app itself as the preview',
    title: 'Theme builder',
    defaultName: 'My theme',
    themeName: 'Theme',
    base: 'Start from',
    baseHint: 'Its colours become your starting palette, and its stylesheet sits under yours.',
    scratch: 'Slack’s own colours',

    // The screen the window opens on
    startTitle: 'Theme builder',
    startBody: 'Slack itself is the preview: everything you change here repaints the client next door, live.',
    startNew: 'Start a new theme',
    startNewOn: 'Two colours, ten derived, on top of {theme} — which is what you are wearing now.',
    startNewScratch: 'Two colours, ten derived, on top of Slack’s own palette.',
    startPick: 'Start from',
    startOn: 'On now',
    startEdit: 'Open its palette',
    startThemeActive: '{name} (on now)',
    startCopyName: '{name}, edited',
    startResume: 'Carry on where you left off',
    startResumeMeta: '{name} — {when} — {tokens} tokens taken over',
    startResumeGo: 'Resume',
    startFoot: 'While this window is open your own themes are held back, so what you see is what you are building. Closing it puts them straight back.',

    palette: 'Palette',
    paletteRail: 'Two colours, ten derived',
    inspect: 'Inspect',
    inspectRail: 'Find out what paints what',
    inspectHint: 'Point at anything in the app and edit the tokens that paint it.',
    tokens: 'Tokens',
    tokensRail: 'Every colour in the client',
    tokensHint: 'Read out of the running client, so a Slack release that adds colours adds them here.',
    code: 'Code',
    codeRail: 'Your own CSS, and the output',


    // The twelve roles: what each is called, and what it paints.
    role_bg: 'Background',
    role_bg_hint: 'The conversation',
    role_accent: 'Accent',
    role_accent_hint: 'Links, focus, active tab',
    role_chrome: 'Chrome',
    role_chrome_hint: 'Rail and sidebar',
    role_raised: 'Raised',
    role_raised_hint: 'Composer, menus',
    role_surface: 'Surface',
    role_surface_hint: 'Dividers, pills',
    role_selected: 'Selected',
    role_selected_hint: 'Open channel',
    role_hover: 'Hover',
    role_hover_hint: 'Row under the pointer',
    role_text: 'Text',
    role_text_hint: 'Message body',
    role_bright: 'Headings',
    role_bright_hint: 'Names and titles',
    role_muted: 'Muted',
    role_muted_hint: 'Timestamps',
    role_accentText: 'Accent text',
    role_accentText_hint: 'Mentions',
    role_danger: 'Danger',
    role_danger_hint: 'Badges',

    seedsTitle: 'The two that decide',
    seedsHint: 'A background and an accent. Everything else follows from these.',
    derivedTitle: 'Derived',
    derivedHint: 'Worked out from the two above. Click any to take it over.',
    own: 'Yours',
    rederiveOne: 'Derive it again',
    reroll: 'Derive them all again',
    rerollHint: 'Throw away the ones you took over',
    contrastTitle: 'Readability',
    contrastHint: 'Real text in the pairs Slack really puts together, judged against WCAG.',
    checkMessage: 'Message text on the conversation',
    checkTimestamps: 'Timestamps on the conversation',
    checkSidebar: 'Sidebar titles on the rail',
    checkMentions: 'A mention in a message',

    // Inspect
    picked: 'What you picked',
    copySelector: 'Copy this selector',
    qaStable: 'data-qa is Slack’s own hook — it survives releases.',
    classes: 'Its classes',
    classStable: 'Copy. This kind of name is stable across releases.',
    classVolatile: 'Copy. Hashed name: it changes with every Slack build.',
    around: 'Around it',
    paintedByHint: 'Hover a token to light up everything it paints. Click to change it.',
    editToken: 'Change this token',
    copyValue: 'Copy this value',

    pick: 'Point at something',
    picking: 'Click an element… (Esc cancels)',
    nothingTitle: 'Nothing picked yet',
    nothing: 'Point at anything in Slack — a channel row, a message, the composer — and every token that paints it lands here, editable, with the elements around it one click away.',
    paintedBy: 'Painted by',
    noVars: 'No token paints this one: the colour is written literally, or inherited from a parent.',
    computed: 'Ends up as',
    background: 'Background',
    text: 'Text',
    matchedRules: '{count} rules match it',

    searchTokens: 'Search tokens…',
    allFamilies: 'All',
    ownOnly: 'Taken over only',
    family_chrome: 'Chrome',
    family_content: 'Content',
    family_legacy: 'Legacy',
    family_palette: 'Palette',
    family_other: 'Other',
    family_chrome_hint: 'Rail, sidebar, headers. Needs !important, which is handled for you.',
    family_content_hint: 'Messages, controls, text.',
    family_legacy_hint: 'Older components. Bare "r, g, b" triplets.',
    family_palette_hint: 'The raw palette everything else is built from.',
    family_other_hint: 'Everything that did not fit the four.',
    tokenCount: 'Showing {shown} of {total} — {own} taken over',
    showMore: 'Show more',
    noMatchTitle: 'Nothing matches',
    noMatch: 'No token in this family has that in its name.',
    drop: 'Give it back to Slack',

    yourRules: 'Your own rules',
    cssHint: 'Anything a palette cannot say. Lands after everything else, so it wins.',
    output: 'The stylesheet',
    outputHint: 'Exactly what Save writes and Copy copies.',
    outputStats: '{lines} lines — {tokens} tokens taken over',

    reset: 'Reset',
    resetHint: 'Throw away everything and start from Slack’s colours',
    resetTitle: 'Reset the theme?',
    resetBody: 'The palette, every token you took over and your own CSS go back to how they started. Themes you have already saved are untouched.',
    resetConfirm: 'Reset everything',
    cancel: 'Cancel',
    wasReset: 'Back to where you started.',
    save: 'Save theme',
    saved: 'Saved — it is in your Themes list.',
    savedDescription: 'A theme built with BetterSlack’s theme builder.',
    needsName: 'Give the theme a name first.',
    importTheme: 'Import…',
    importHint: 'Open a .css someone sent you, and edit it from here',
    imported: 'Imported {name} — its colours are in the palette.',
    exportTheme: 'Export',
    exportHint: 'Write this theme to a file you can hand to someone',
    exported: 'Written to your downloads.',
    copy: 'Copy CSS',
    copied: 'Theme CSS copied',
    suspend: 'Compare',
    resume: 'Back to mine',
    suspendHint: 'Hold Slack at how it normally looks, so you can see what your theme changed. Nothing here is lost.',
    suspended: 'Showing Slack as it normally is — press again to come back.',

    blocked: 'Slack refused to open a window. Allow pop-ups for the app.',
    already: 'The builder is already open.',
  },

  fr: {
    open: 'Constructeur de thème',
    openHint: 'Concevoir un thème avec l’application elle-même comme aperçu',
    title: 'Constructeur de thème',
    defaultName: 'Mon thème',
    themeName: 'Thème',
    base: 'Partir de',
    baseHint: 'Ses couleurs deviennent votre palette de départ, et sa feuille de style passe sous la vôtre.',
    scratch: 'Les couleurs de Slack',

    // L’écran d’ouverture de la fenêtre
    startTitle: 'Constructeur de thème',
    startBody: 'Slack est l’aperçu : tout ce que vous changez ici repeint le client d’à côté, en direct.',
    startNew: 'Créer un nouveau thème',
    startNewOn: 'Deux couleurs, dix déduites, par-dessus {theme} — celui que vous portez en ce moment.',
    startNewScratch: 'Deux couleurs, dix déduites, par-dessus la palette de Slack.',
    startPick: 'Partir de',
    startOn: 'Actif',
    startEdit: 'Ouvrir sa palette',
    startThemeActive: '{name} (actif)',
    startCopyName: '{name}, modifié',
    startResume: 'Reprendre où vous en étiez',
    startResumeMeta: '{name} — {when} — {tokens} tokens personnalisés',
    startResumeGo: 'Reprendre',
    startFoot: 'Tant que cette fenêtre est ouverte, vos propres thèmes sont mis de côté : ce que vous voyez est ce que vous construisez. La fermer les remet aussitôt.',

    palette: 'Palette',
    paletteRail: 'Deux couleurs, dix déduites',
    inspect: 'Inspecter',
    inspectRail: 'Savoir qui peint quoi',
    inspectHint: 'Pointez n’importe quoi dans l’app et modifiez les tokens qui le peignent.',
    tokens: 'Tokens',
    tokensRail: 'Toutes les couleurs du client',
    tokensHint: 'Lus dans le client en cours d’exécution : une version de Slack qui ajoute des couleurs les ajoute ici.',
    code: 'Code',
    codeRail: 'Votre CSS, et le résultat',


    // The twelve roles: what each is called, and what it paints.
    role_bg: 'Fond',
    role_bg_hint: 'La conversation',
    role_accent: 'Accent',
    role_accent_hint: 'Liens, focus, onglet actif',
    role_chrome: 'Chrome',
    role_chrome_hint: 'Rail et barre latérale',
    role_raised: 'Surélevé',
    role_raised_hint: 'Zone de saisie, menus',
    role_surface: 'Surface',
    role_surface_hint: 'Séparateurs, pastilles',
    role_selected: 'Sélection',
    role_selected_hint: 'Canal ouvert',
    role_hover: 'Survol',
    role_hover_hint: 'La ligne sous le curseur',
    role_text: 'Texte',
    role_text_hint: 'Corps des messages',
    role_bright: 'Titres',
    role_bright_hint: 'Noms et intitulés',
    role_muted: 'Discret',
    role_muted_hint: 'Horodatages',
    role_accentText: 'Texte d’accent',
    role_accentText_hint: 'Mentions',
    role_danger: 'Alerte',
    role_danger_hint: 'Pastilles de notification',

    seedsTitle: 'Les deux qui décident',
    seedsHint: 'Un fond et une couleur d’accent. Tout le reste en découle.',
    derivedTitle: 'Déduites',
    derivedHint: 'Calculées à partir des deux couleurs ci-dessus. Cliquez sur l’une d’elles pour la personnaliser.',
    own: 'Personnalisé',
    rederiveOne: 'Redéduire',
    reroll: 'Tout redéduire',
    rerollHint: 'Oublier les couleurs que vous avez personnalisées',
    contrastTitle: 'Lisibilité',
    contrastHint: 'Du vrai texte dans les paires que Slack met réellement ensemble, jugé selon WCAG.',
    checkMessage: 'Texte d’un message sur la conversation',
    checkTimestamps: 'Horodatage sur la conversation',
    checkSidebar: 'Titres de la barre latérale',
    checkMentions: 'Une mention dans un message',

    // Inspect
    picked: 'Ce que vous avez pointé',
    copySelector: 'Copier ce sélecteur',
    qaStable: 'data-qa est le repère de Slack — il survit aux mises à jour.',
    classes: 'Ses classes',
    classStable: 'Copier. Ce type de nom est stable d’une version à l’autre.',
    classVolatile: 'Copier. Nom haché : il change à chaque build de Slack.',
    around: 'Autour',
    paintedByHint: 'Survolez un token pour voir tout ce qu’il peint. Cliquez pour le changer.',
    editToken: 'Modifier ce token',
    copyValue: 'Copier cette valeur',

    pick: 'Pointer un élément',
    picking: 'Cliquez un élément… (Échap annule)',
    nothingTitle: 'Rien de sélectionné',
    nothing: 'Pointez n’importe quoi dans Slack — une ligne de canal, un message, la zone de saisie — et tous les tokens qui le peignent arrivent ici, modifiables, avec les éléments autour à un clic.',
    paintedBy: 'Peint par',
    noVars: 'Aucun token ne le peint : la couleur est écrite en dur, ou héritée d’un parent.',
    computed: 'Résultat',
    background: 'Fond',
    text: 'Texte',
    matchedRules: '{count} règles le visent',

    searchTokens: 'Rechercher un token…',
    allFamilies: 'Toutes',
    ownOnly: 'Personnalisés seulement',
    family_chrome: 'Chrome',
    family_content: 'Contenu',
    family_legacy: 'Héritée',
    family_palette: 'Palette',
    family_other: 'Autres',
    family_chrome_hint: 'Rail, barre latérale, en-têtes. Demande !important, ajouté pour vous.',
    family_content_hint: 'Messages, contrôles, texte.',
    family_legacy_hint: 'Composants hérités des anciennes versions. Triplets « r, g, b » bruts.',
    family_palette_hint: 'La palette brute dont tout le reste est tiré.',
    family_other_hint: 'Tout ce qui n’entrait pas dans les quatre.',
    tokenCount: '{shown} sur {total} affichés — {own} personnalisés',
    showMore: 'En afficher plus',
    noMatchTitle: 'Aucun résultat',
    noMatch: 'Aucun token de cette famille ne porte cela dans son nom.',
    drop: 'Le rendre à Slack',

    yourRules: 'Vos propres règles',
    cssHint: 'Tout ce qu’une palette ne sait pas exprimer. Appliqué après tout le reste, il l’emporte donc.',
    output: 'La feuille de style',
    outputHint: 'Exactement ce qu’Enregistrer écrit et ce que Copier copie.',
    outputStats: '{lines} lignes — {tokens} tokens personnalisés',

    reset: 'Réinitialiser',
    resetHint: 'Tout jeter et repartir des couleurs de Slack',
    resetTitle: 'Réinitialiser le thème ?',
    resetBody: 'La palette, tous les tokens que vous avez repris et votre CSS reviennent à leur état de départ. Les thèmes déjà enregistrés ne sont pas touchés.',
    resetConfirm: 'Tout réinitialiser',
    cancel: 'Annuler',
    wasReset: 'Retour au point de départ.',
    save: 'Enregistrer le thème',
    saved: 'Enregistré — il est dans vos thèmes.',
    savedDescription: 'Un thème conçu avec le constructeur de thèmes de BetterSlack.',
    needsName: 'Donnez d’abord un nom au thème.',
    importTheme: 'Importer…',
    importHint: 'Ouvrir un .css qu’on vous a envoyé, et l’éditer d’ici',
    imported: '{name} importé — ses couleurs sont dans la palette.',
    exportTheme: 'Exporter',
    exportHint: 'Écrire ce thème dans un fichier à transmettre',
    exported: 'Écrit dans vos téléchargements.',
    copy: 'Copier le CSS',
    copied: 'CSS du thème copié',
    suspend: 'Comparer',
    resume: 'Revenir au mien',
    suspendHint: 'Remettre Slack tel qu’il est normalement, pour voir ce que votre thème change. Rien n’est perdu ici.',
    suspended: 'Slack tel qu’il est normalement — appuyez à nouveau pour revenir.',

    blocked: 'Slack a refusé d’ouvrir une fenêtre. Autorisez les fenêtres pop-up pour l’application.',
    already: 'Le constructeur est déjà ouvert.',
  },
};
