// Everything the builder says, in every language it says it in.
//
// English is required and is what a missing language or key falls back to.
// Apart from the code so a translator never has to read any of it.

export const STRINGS = {
  en: {
    open: 'Theme builder',
    openHint: 'Design a theme with the app itself as the preview',
    title: 'Theme builder',
    defaultName: 'My theme',
    base: 'Start from',
    baseHint: 'A theme to build on top of. Yours is applied over it.',
    scratch: 'Slack’s own colours',
    save: 'Save',
    saved: 'Saved — it is in your Themes list.',
    savedDescription: 'A theme built with SlackMod’s theme builder.',
    needsName: 'Give the theme a name first.',
    copy: 'Copy CSS',
    copied: 'Theme CSS copied',
    suspend: 'Suspend',
    resume: 'Resume',
    suspendHint: 'Put Slack back to how it was, without losing anything here',

    palette: 'Palette',
    paletteHint: 'two colours, ten derived',
    derived: 'Derived from those two — click any to take it over.',
    reroll: 'Re-derive',
    rerollHint: 'Throw away the ones you took over and derive the ten again',

    inspect: 'Inspect',
    inspectHint: 'what paints what',
    pick: 'Point at something in Slack',
    picking: 'Click an element… (Escape cancels)',
    nothing: 'Nothing picked yet. Point at anything in Slack and every token that paints it lands here, editable.',
    paintedBy: 'Painted by',
    noVars: 'No token paints this one — it is a literal colour, or it inherits.',
    computed: 'Ends up as',
    background: 'Background',
    text: 'Text',
    matchedRules: '{count} rules match it',

    tokens: 'All tokens',
    tokensHint: 'every colour the client defines',
    searchTokens: 'Search tokens…',
    allFamilies: 'Every family',
    familyChrome: 'Chrome',
    familyContent: 'Content',
    familyLegacy: 'Legacy',
    familyPalette: 'Palette',
    familyOther: 'Other',
    tokenCount: 'Showing {shown} of {total} — {own} taken over',
    drop: 'Give it back to Slack',

    cssHint: 'Rules of your own. They land after everything above, so they win.',

    blocked: 'Slack refused to open a window. Allow pop-ups for the app.',
    already: 'The builder is already open.',
  },

  fr: {
    open: 'Constructeur de thème',
    openHint: 'Concevoir un thème avec l’application elle-même comme aperçu',
    title: 'Constructeur de thème',
    defaultName: 'Mon thème',
    base: 'Partir de',
    baseHint: 'Un thème comme base. Le vôtre s’applique par-dessus.',
    scratch: 'Les couleurs de Slack',
    save: 'Enregistrer',
    saved: 'Enregistré — il est dans vos thèmes.',
    savedDescription: 'Un thème conçu avec le constructeur de thèmes de SlackMod.',
    needsName: 'Donnez d’abord un nom au thème.',
    copy: 'Copier le CSS',
    copied: 'CSS du thème copié',
    suspend: 'Suspendre',
    resume: 'Reprendre',
    suspendHint: 'Remettre Slack comme avant, sans rien perdre ici',

    palette: 'Palette',
    paletteHint: 'deux couleurs, dix déduites',
    derived: 'Déduites de ces deux-là — cliquez pour en reprendre une.',
    reroll: 'Redéduire',
    rerollHint: 'Oublier celles que vous avez reprises et redéduire les dix',

    inspect: 'Inspecter',
    inspectHint: 'qui peint quoi',
    pick: 'Pointer un élément de Slack',
    picking: 'Cliquez un élément… (Échap annule)',
    nothing: 'Rien de sélectionné. Pointez n’importe quoi dans Slack : tous les tokens qui le peignent arrivent ici, modifiables.',
    paintedBy: 'Peint par',
    noVars: 'Aucun token ne le peint — couleur écrite en dur, ou héritée.',
    computed: 'Résultat',
    background: 'Fond',
    text: 'Texte',
    matchedRules: '{count} règles le visent',

    tokens: 'Tous les tokens',
    tokensHint: 'toutes les couleurs du client',
    searchTokens: 'Rechercher un token…',
    allFamilies: 'Toutes les familles',
    familyChrome: 'Chrome',
    familyContent: 'Contenu',
    familyLegacy: 'Ancienne',
    familyPalette: 'Palette',
    familyOther: 'Autres',
    tokenCount: '{shown} sur {total} affichés — {own} repris',
    drop: 'Le rendre à Slack',

    cssHint: 'Vos propres règles. Elles arrivent après tout le reste, donc elles gagnent.',

    blocked: 'Slack a refusé d’ouvrir une fenêtre. Autorisez les fenêtres surgissantes.',
    already: 'Le constructeur est déjà ouvert.',
  },
};
