// What the column says, in every language it says it in.
//
// English is required and is what a missing language or key falls back to;
// api.i18n.strings() does the lookup. Kept apart from the code so a translator
// can add a language without reading any of it.

export const STRINGS = {
  en: {
    loading: 'Loading…',
    members: 'Members',
    online: 'Online',
    offline: 'Offline',
    noMembers: 'Slack does not list members for this conversation.',
    noToken: 'No Slack session token in this window.',
    presenceCap:
      'Online status covers the first {count}. Slack answers about one person per request, and ' +
      'asking about everyone here would hit its rate limit.',
    profile: 'Profile',
    active: 'Active',
    away: 'Away',
    localTime: '{time} local time',
    dnd: 'Do not disturb',
    message: 'Message',
    huddle: 'Huddle',
    noHuddle: 'Slack offers no huddle for this conversation.',
    more: 'More actions',
    viewFiles: 'View files',
    openInSlack: 'Open profile in Slack',
    addVip: 'Add to VIPs',
    removeVip: 'Remove from VIPs',
    vipAdded: 'Added to your VIPs',
    vipRemoved: 'Removed from your VIPs',
    hide: 'Hide conversation',
    hidden: 'Conversation hidden',
    noFiles: 'Nothing shared yet.',
    filesTitle: 'Files from {name}',
    actionFailed: 'Slack refused that: {reason}',
    displayName: 'Display name',
    fullName: 'Full name',
    title: 'Title',
    email: 'Email',
    phone: 'Phone',
    timeZone: 'Time zone',
    username: 'Username',
    memberId: 'Member ID',
    copyName: 'Copy name',
    copyId: 'Copy member ID',
    copyLink: 'Copy profile link',
    copiedName: 'Copied the display name',
    copiedId: 'Copied the member ID',
    copiedLink: 'Copied the profile link',
    statusUntil: 'until {time}',
    noMemberList: 'Slack is not showing a member list for this conversation.',
    profileRefused: 'Slack did not open that profile. Its window may be in the background.',
    notOffered: 'Slack does not offer that for this person.',
    refused: 'Slack refused the request: {reason}',
  },
  fr: {
    loading: 'Chargement…',
    members: 'Membres',
    online: 'En ligne',
    offline: 'Hors ligne',
    noMembers: 'Slack ne fournit pas la liste des membres de cette conversation.',
    noToken: 'Aucun jeton de session Slack dans cette fenêtre.',
    presenceCap:
      'La disponibilité n’est affichée que pour les {count} premiers : Slack ne répond que pour ' +
      'une personne à la fois, et les demander toutes ferait dépasser sa limite de requêtes.',
    profile: 'Profil',
    active: 'Disponible',
    away: 'Absent',
    localTime: '{time} heure locale',
    dnd: 'Ne pas déranger',
    message: 'Message',
    huddle: 'Appel d’équipe',
    noHuddle: 'Slack ne propose pas d’appel d’équipe pour cette conversation.',
    more: 'Plus d’actions',
    viewFiles: 'Voir les fichiers',
    openInSlack: 'Ouvrir le profil dans Slack',
    addVip: 'Ajouter aux VIP',
    removeVip: 'Retirer des VIP',
    vipAdded: 'Ajouté à vos VIP',
    vipRemoved: 'Retiré de vos VIP',
    hide: 'Masquer la conversation',
    hidden: 'Conversation masquée',
    noFiles: 'Rien de partagé pour l’instant.',
    filesTitle: 'Fichiers de {name}',
    actionFailed: 'Slack a refusé : {reason}',
    displayName: 'Nom d’affichage',
    fullName: 'Nom complet',
    title: 'Fonction',
    email: 'E-mail',
    phone: 'Téléphone',
    timeZone: 'Fuseau horaire',
    username: 'Nom d’utilisateur',
    memberId: 'ID de membre',
    copyName: 'Copier le nom',
    copyId: 'Copier l’ID de membre',
    copyLink: 'Copier le lien du profil',
    copiedName: 'Nom d’affichage copié',
    copiedId: 'ID de membre copié',
    copiedLink: 'Lien du profil copié',
    statusUntil: 'jusqu’à {time}',
    noMemberList: 'Slack n’affiche pas de liste de membres pour cette conversation.',
    profileRefused: 'Slack n’a pas ouvert ce profil. Sa fenêtre est peut-être en arrière-plan.',
    notOffered: 'Slack ne propose pas cette action pour cette personne.',
    refused: 'Slack a refusé la requête : {reason}',
  },
};
