// What the plugin says, in every language it says it in.
//
// English is required and is what a missing language or key falls back to;
// api.i18n.strings() does the lookup. `status_<status>` and `error_<reason>`
// are looked up by key from what GitLab or the client reports, so a new one is
// a new line in each table and nothing else.
//
// The French addresses nobody in particular, rather than choosing between tu
// and vous for a reader it does not know.

export const STRINGS = {
  en: {
    railLabel: 'GitLab',
    viewTitle: 'My merge requests',
    commandOpen: 'Open GitLab Merge Requests',
    commandRefresh: 'Refresh GitLab',

    // signing in
    loginTitle: 'Connect to GitLab',
    loginIntro: 'Your open merge requests and the stages of their pipelines, without leaving Slack. A read-only token is enough.',
    fieldServer: 'GitLab address',
    fieldToken: 'Personal access token',
    tokenHint: 'Create one in GitLab under Preferences, Access tokens, with only the read_api scope. BetterSlack keeps it in its own folder, readable only by you, and sends it to this address and nowhere else.',
    submit: 'Connect',
    submitting: 'Connecting…',
    privacy: 'Nothing from Slack is ever sent to GitLab: no message, no channel, no workspace.',
    sessionInvalid: 'GitLab no longer accepts your token. Connect again with a new one.',
    connectedAs: 'Connected as {name} (@{username})',
    signOut: 'Disconnect',

    error_address: 'That is not an address BetterSlack can use. It has to be https, like https://gitlab.example.com.',
    error_tokenFormat: 'That does not look like a token: no spaces, at least 8 characters.',
    error_unauthorized: 'GitLab did not accept this token. It may be wrong, expired or revoked.',
    error_forbidden: 'This token may not read the API. It needs the read_api scope.',
    error_notFound: 'GitLab does not know that address. Check it is the one you sign in at.',
    error_rateLimited: 'GitLab is asking for fewer requests. BetterSlack will try again shortly.',
    error_server: 'GitLab had an internal error. BetterSlack will try again shortly.',
    error_timeout: 'GitLab took too long to answer.',
    error_unreachable: 'GitLab could not be reached.',
    error_redirect: 'GitLab answered with a redirect. Check the address is the one you sign in at.',
    error_unexpected: 'GitLab answered with something BetterSlack does not understand.',
    error_blocked: 'BetterSlack refused the request. Is the plugin on, and is this the address in its settings?',
    error_inaccessible: 'This merge request’s pipelines cannot be read any more.',
    error_pagination: 'The list stops at 500 merge requests.',

    // the view
    refresh: 'Refresh',
    collapseProject: 'Collapse {name}',
    expandProject: 'Expand {name}',
    collapseAll: 'Collapse all',
    expandAll: 'Expand all',
    summaryFailed: '{count} failed',
    summaryRunning: '{count} running',
    refreshing: 'Refreshing…',
    loading: 'Loading your merge requests…',
    updatedAt: 'Updated {time}',
    staleNote: 'GitLab cannot be reached: {reason} Showing what was last known, from {time}.',
    partialNote: 'The list may be incomplete. {reason}',
    empty: 'No open merge requests.',
    emptyHint: 'The ones you open on GitLab will appear here.',
    draft: 'Draft',
    branches: '{source} → {target}',
    noPipeline: 'No pipeline',
    pipelineNumber: 'Pipeline #{id}',
    openMr: 'Open merge request !{iid} on GitLab',
    openProject: 'Open project {name} on GitLab',
    openPipeline: 'Open pipeline #{id} on GitLab',
    openJob: 'Open job {name} on GitLab',
    pipelineLoading: 'Stages loading…',
    mrCount_one: '{count} open merge request',
    mrCount_many: '{count} open merge requests',

    // time
    justNow: 'just now',
    minutesAgo: '{count} min ago',
    hoursAgo: '{count} h ago',
    daysAgo: '{count} d ago',
    seconds: '{s}s',
    minutesSeconds: '{m}m {s}s',

    // statuses
    status_created: 'Created',
    status_waiting_for_resource: 'Waiting for a runner',
    status_preparing: 'Preparing',
    status_pending: 'Pending',
    status_running: 'Running',
    status_canceling: 'Canceling',
    status_success: 'Passed',
    status_failed: 'Failed',
    status_canceled: 'Canceled',
    status_skipped: 'Skipped',
    status_manual: 'Waiting for you',
    status_scheduled: 'Scheduled',
    status_warning: 'Failed, allowed',

    // stages and jobs
    stageLabel: '{stage}: {status}',
    jobsEmpty: 'No jobs yet.',
    jobsManual: 'Manual: it runs when you start it.',
    progressLabel: '{done}/{total}',
    progressManual: '{count} manual',
    progressSkipped: '{count} skipped',
    progressTitle: '{done} of {total} jobs finished',

    // the top bar
    barSignIn: 'GitLab · Connect',
    barInvalid: 'GitLab · Connect again',
    barLoading: 'GitLab…',
    barEmpty: 'GitLab · 0 open MR',
    barNoPipeline: 'GitLab · {count} MR · no pipeline',
    barStale: 'Not up to date',
    barFailed: '{job} failed',
    barLabel: 'GitLab: {project} !{iid}, {status}',
    recentTitle: 'Latest pipelines',
    actionMr: 'Merge request',
    actionPipeline: 'Pipeline',
    barUnfold: 'Show the latest pipelines',
    recentEmpty: 'No pipeline yet on your open merge requests.',
    seeMore: 'See more',
  },
  fr: {
    railLabel: 'GitLab',
    viewTitle: 'Mes merge requests',
    commandOpen: 'Ouvrir les Merge Requests GitLab',
    commandRefresh: 'Actualiser GitLab',

    loginTitle: 'Se connecter à GitLab',
    loginIntro: 'Vos merge requests ouvertes et les étapes de leurs pipelines, sans quitter Slack. Un jeton en lecture seule suffit.',
    fieldServer: 'Adresse de GitLab',
    fieldToken: 'Jeton d’accès personnel',
    tokenHint: 'Créez-en un dans GitLab, sous Préférences, Jetons d’accès, avec le seul périmètre read_api. BetterSlack le garde dans son propre dossier, lisible par vous seul, et ne l’envoie qu’à cette adresse.',
    submit: 'Se connecter',
    submitting: 'Connexion…',
    privacy: 'Rien de Slack n’est jamais envoyé à GitLab : ni message, ni canal, ni espace de travail.',
    sessionInvalid: 'GitLab n’accepte plus votre jeton. Reconnectez-vous avec un nouveau.',
    connectedAs: 'Connecté en tant que {name} (@{username})',
    signOut: 'Se déconnecter',

    error_address: 'Cette adresse ne peut pas être utilisée par BetterSlack. Elle doit être en https, comme https://gitlab.exemple.com.',
    error_tokenFormat: 'Cela ne ressemble pas à un jeton : sans espace, au moins 8 caractères.',
    error_unauthorized: 'GitLab n’a pas accepté ce jeton. Il est peut-être erroné, expiré ou révoqué.',
    error_forbidden: 'Ce jeton ne peut pas lire l’API. Il lui faut le périmètre read_api.',
    error_notFound: 'GitLab ne connaît pas cette adresse. Vérifiez que c’est celle de votre connexion.',
    error_rateLimited: 'GitLab demande moins de requêtes. BetterSlack réessaiera sous peu.',
    error_server: 'GitLab a eu une erreur interne. BetterSlack réessaiera sous peu.',
    error_timeout: 'GitLab a mis trop de temps à répondre.',
    error_unreachable: 'GitLab est injoignable.',
    error_redirect: 'GitLab a répondu par une redirection. Vérifiez que l’adresse est celle de votre connexion.',
    error_unexpected: 'GitLab a répondu quelque chose que BetterSlack ne comprend pas.',
    error_blocked: 'BetterSlack a refusé la requête. Le plugin est-il activé, et est-ce l’adresse de ses réglages ?',
    error_inaccessible: 'Les pipelines de cette merge request ne sont plus lisibles.',
    error_pagination: 'La liste s’arrête à 500 merge requests.',

    refresh: 'Actualiser',
    collapseProject: 'Replier {name}',
    expandProject: 'Déplier {name}',
    collapseAll: 'Tout replier',
    expandAll: 'Tout déplier',
    summaryFailed: '{count} en échec',
    summaryRunning: '{count} en cours',
    refreshing: 'Actualisation…',
    loading: 'Chargement de vos merge requests…',
    updatedAt: 'Mis à jour {time}',
    staleNote: 'GitLab est injoignable : {reason} Affichage du dernier état connu, de {time}.',
    partialNote: 'La liste est peut-être incomplète. {reason}',
    empty: 'Aucune merge request ouverte.',
    emptyHint: 'Celles que vous ouvrez sur GitLab apparaîtront ici.',
    draft: 'Brouillon',
    branches: '{source} → {target}',
    noPipeline: 'Aucune pipeline',
    pipelineNumber: 'Pipeline n° {id}',
    openMr: 'Ouvrir la merge request !{iid} sur GitLab',
    openProject: 'Ouvrir le projet {name} sur GitLab',
    openPipeline: 'Ouvrir la pipeline n° {id} sur GitLab',
    openJob: 'Ouvrir le job {name} sur GitLab',
    pipelineLoading: 'Chargement des étapes…',
    mrCount_one: '{count} merge request ouverte',
    mrCount_many: '{count} merge requests ouvertes',

    justNow: 'à l’instant',
    minutesAgo: 'il y a {count} min',
    hoursAgo: 'il y a {count} h',
    daysAgo: 'il y a {count} j',
    seconds: '{s} s',
    minutesSeconds: '{m} min {s} s',

    status_created: 'Créée',
    status_waiting_for_resource: 'En attente d’un runner',
    status_preparing: 'Préparation',
    status_pending: 'En attente',
    status_running: 'En cours',
    status_canceling: 'Annulation',
    status_success: 'Réussie',
    status_failed: 'Échouée',
    status_canceled: 'Annulée',
    status_skipped: 'Ignorée',
    status_manual: 'En attente de vous',
    status_scheduled: 'Planifiée',
    status_warning: 'Échec autorisé',

    stageLabel: '{stage} : {status}',
    jobsEmpty: 'Aucun job pour le moment.',
    jobsManual: 'Manuel : il s’exécute quand vous le lancez.',
    progressLabel: '{done}/{total}',
    progressManual: '{count} manuel(s)',
    progressSkipped: '{count} ignoré(s)',
    progressTitle: '{done} jobs terminés sur {total}',

    barSignIn: 'GitLab · Se connecter',
    barInvalid: 'GitLab · Se reconnecter',
    barLoading: 'GitLab…',
    barEmpty: 'GitLab · 0 MR ouverte',
    barNoPipeline: 'GitLab · {count} MR · aucune pipeline',
    barStale: 'Pas à jour',
    barFailed: '{job} en échec',
    barLabel: 'GitLab : {project} !{iid}, {status}',
    recentTitle: 'Dernières pipelines',
    actionMr: 'Merge request',
    actionPipeline: 'Pipeline',
    barUnfold: 'Voir les dernières pipelines',
    recentEmpty: 'Aucune pipeline pour le moment sur vos merge requests ouvertes.',
    seeMore: 'Voir plus',
  },
};
