export const STRINGS = {
  en: {
    button: 'Edit log',
    buttonHint: 'What messages said before they were changed',
    commandSubtitle: 'What messages said before they were changed',
    title: 'Edit log',
    subtitle: 'Kept on this machine, in BetterSlack’s own settings file. Nothing is sent anywhere.',
    empty: 'Nothing recorded yet.',
    emptyHint: 'This watches the conversations you have open, so it fills up as you read. A message changed while you were elsewhere was never on your screen, and is not here.',
    edited: 'edited',
    deleted: 'deleted',
    before: 'Before',
    after: 'After',
    deletedNote: 'The message is gone from Slack. This is what it said.',
    jump: 'Go to it',
    copy: 'Copy the old text',
    copied: 'Copied',
    clear: 'Clear',
    clearTitle: 'Clear the log?',
    clearBody: 'All {count} entries go, and they are not kept anywhere else.',
    cleared: 'Log cleared',
    close: 'Close',
    someone: 'Someone',
    inChannel: 'in {channel}',
    watching: 'Watching {count} messages on screen.',
    entries: '{count} recorded',
  },
  fr: {
    button: 'Journal des éditions',
    buttonHint: 'Ce que les messages disaient avant d’être modifiés',
    commandSubtitle: 'Ce que les messages disaient avant d’être modifiés',
    title: 'Journal des éditions',
    subtitle: 'Conservé sur cette machine, dans le fichier de réglages de BetterSlack. Rien n’est envoyé nulle part.',
    empty: 'Rien d’enregistré pour l’instant.',
    emptyHint: 'Le journal observe les conversations que vous ouvrez, il se remplit donc à mesure que vous lisez. Un message modifié pendant que vous étiez ailleurs n’est jamais passé par votre écran, et n’est pas ici.',
    edited: 'modifié',
    deleted: 'supprimé',
    before: 'Avant',
    after: 'Après',
    deletedNote: 'Le message n’est plus dans Slack. Voici ce qu’il disait.',
    jump: 'Y aller',
    copy: 'Copier l’ancien texte',
    copied: 'Copié',
    clear: 'Effacer',
    clearTitle: 'Effacer le journal ?',
    clearBody: 'Les {count} entrées disparaissent, et elles ne sont conservées nulle part ailleurs.',
    cleared: 'Journal effacé',
    close: 'Fermer',
    someone: 'Quelqu’un',
    inChannel: 'dans {channel}',
    watching: '{count} messages suivis à l’écran.',
    entries: '{count} enregistrées',
  },
};
