#!/usr/bin/env node
// The catalogue, as the site sees it.
//
//   pnpm site
//
// The presentation site lists every theme and plugin, and a list of mods
// maintained by hand next to a list of mods maintained by the repository is a
// list that goes stale on the first pull request. So it is generated from
// `mods/registry.json` -- the same file the app installs from -- into a single
// `site/data.js` the page loads.
//
// The colour strips under each theme come from the theme's own stylesheet,
// through the reader the theme builder already uses for its gallery. One
// parser, so the site and the builder can never disagree about what a theme's
// palette is.

import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { buildApiPage, buildThemeTokens, bundlePreviews } from './build-api-page.mjs';
import { stripFrom } from '../mods/plugins/theme-builder/read-theme.js';
import { formatCss } from '../mods/plugins/theme-builder/colour.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const registry = JSON.parse(readFileSync(path.join(root, 'mods/registry.json'), 'utf8'));
const pkg = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'));

/*
 * Where a mod's own picture is copied to.
 *
 * The catalogue and the panel show the same frame, out of the same file:
 * `mods/<kind>/<id>/screenshot.webp`, taken by `pnpm shoot --mods`. The page is
 * published on its own, so the file has to be inside `site/` -- copied here
 * rather than listed by hand, which is what the previous table of seven theme
 * crops was, and it went stale the first time a theme was added.
 */
const SHOT_DIR = path.join(root, 'site/shots/mods');
mkdirSync(SHOT_DIR, { recursive: true });

const themes = [];
const plugins = [];

for (const mod of registry.mods) {
  const folder = path.join(root, 'mods', mod.type === 'theme' ? 'themes' : 'plugins', mod.id);
  const entry = {
    id: mod.id,
    name: mod.name,
    description: mod.description,
    // The page reads whichever language the browser asks for and falls back to
    // the English one, exactly as the panel does.
    descriptions: mod.descriptions ?? {},
    version: mod.version,
    tags: mod.tags ?? [],
    requires: mod.requires ?? [],
  };

  /*
   * The mark, inlined.
   *
   * A card without one is a paragraph with a heading; twenty-two of them is a
   * wall. They are a few hundred bytes each and there are twenty-two, so the
   * whole set costs less than one screenshot and needs no extra request.
   */
  if (mod.icon) {
    const icon = readFileSync(path.join(folder, mod.icon), 'utf8').trim();
    if (icon.startsWith('<svg')) entry.icon = icon;
  }

  /*
   * Every frame the mod ships, not only the first: several mods have two or
   * three now, and the panel shows them all. The card on the site still uses
   * the first, which is why the manifest's order is the one that matters.
   */
  for (const [index, declared] of (mod.screenshots ?? []).entries()) {
    const file = path.join(folder, declared.file);
    if (!existsSync(file)) continue;
    const name = index === 0 ? mod.id : `${mod.id}-${index + 1}`;
    copyFileSync(file, path.join(SHOT_DIR, `${name}.webp`));
    if (index === 0) entry.shot = `shots/mods/${name}.webp`;
  }

  if (mod.type === 'theme') {
    const css = readFileSync(path.join(folder, mod.entry ?? 'theme.css'), 'utf8');
    entry.palette = stripFrom(css).map((colour) => formatCss(colour));
    themes.push(entry);
  } else {
    entry.settings = (JSON.parse(readFileSync(path.join(folder, 'mod.json'), 'utf8')).settings ?? []).length;
    plugins.push(entry);
  }
}

const data = { version: pkg.version, themes, plugins };
writeFileSync(
  path.join(root, 'site/data.js'),
  `// Generated by scripts/build-site.mjs from mods/registry.json — do not edit.\n`
  + `window.CATALOGUE = ${JSON.stringify(data, null, 2)};\n`,
);

console.log(`site/data.js: ${themes.length} theme(s), ${plugins.length} plugin(s)`);

/*
 * The API page, built from the API.
 *
 * Here rather than as a script of its own so `pnpm site` means "the site",
 * and so the page cannot be forgotten when the catalogue is regenerated.
 */
await bundlePreviews();
// Tokens first: the page's theme picker is built from what this returns.
buildThemeTokens();
const api = buildApiPage();
console.log(`site/api.html: ${api.entries} entries, ${api.previews} with a preview`);
