#!/usr/bin/env node
// The catalogue, as the site sees it.
//
//   pnpm site
//
// The presentation site lists every theme and plugin, and a list of mods
// maintained by hand next to a list of mods maintained by the repository is a
// list that goes stale on the first pull request. So it is generated from
// `mods/registry.json` -- the same file the app installs from -- into a single
// `site/data.js` the page loads.
//
// The colour strips under each theme come from the theme's own stylesheet,
// through the reader the theme builder already uses for its gallery. One
// parser, so the site and the builder can never disagree about what a theme's
// palette is.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { stripFrom } from '../mods/plugins/theme-builder/read-theme.js';
import { formatCss } from '../mods/plugins/theme-builder/colour.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const registry = JSON.parse(readFileSync(path.join(root, 'mods/registry.json'), 'utf8'));
const pkg = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'));

/** The screenshots that exist, so the page can show one where there is one. */
const SHOTS = {
  aurora: 'shots/crop-aurora.jpg',
  cocoa: 'shots/crop-cocoa.jpg',
  'discord-dark': 'shots/crop-discord-dark.jpg',
  'discord-light': 'shots/crop-discord-light.jpg',
  'focus-rings': 'shots/crop-focus-rings.jpg',
  midnight: 'shots/crop-midnight.jpg',
  terminal: 'shots/crop-terminal.jpg',
};

const themes = [];
const plugins = [];

for (const mod of registry.mods) {
  const folder = path.join(root, 'mods', mod.type === 'theme' ? 'themes' : 'plugins', mod.id);
  const entry = {
    id: mod.id,
    name: mod.name,
    description: mod.description,
    version: mod.version,
    tags: mod.tags ?? [],
    requires: mod.requires ?? [],
  };

  if (mod.type === 'theme') {
    const css = readFileSync(path.join(folder, mod.entry ?? 'theme.css'), 'utf8');
    entry.palette = stripFrom(css).map((colour) => formatCss(colour));
    entry.shot = SHOTS[mod.id] ?? null;
    themes.push(entry);
  } else {
    entry.settings = (JSON.parse(readFileSync(path.join(folder, 'mod.json'), 'utf8')).settings ?? []).length;
    plugins.push(entry);
  }
}

const data = { version: pkg.version, themes, plugins };
writeFileSync(
  path.join(root, 'site/data.js'),
  `// Generated by scripts/build-site.mjs from mods/registry.json — do not edit.\n`
  + `window.CATALOGUE = ${JSON.stringify(data, null, 2)};\n`,
);

console.log(`site/data.js: ${themes.length} theme(s), ${plugins.length} plugin(s)`);
