// What Quelio says, in every language it says it in.
//
// English is required and is what a missing language or key falls back to;
// api.i18n.strings() does the lookup. The day's situations are `status_<key>`,
// the keys `lib/status.js` answers with, so a new situation is a new line in
// each table and nothing else.
//
// The French addresses nobody in particular -- "Départ possible", "Reprise
// nécessaire" -- rather than choosing between tu and vous for a reader it does
// not know.

export const STRINGS = {
  en: {
    title: 'Quelio',

    hours: '{h}h',
    hoursMinutes: '{h}h {mm}m',
    minutes: '{m} min',
    percent: '{value}%',
    range: '{from}–{to}',
    until: 'until {to}',
    weekTotal: '{done} / {target}',
    weekRemaining: '· {remaining} left',
    barLabel: 'Quelio: {done} of {target} this week. {status}',

    barSignIn: 'Quelio · Sign in',
    barSignInAgain: 'Quelio · Sign in again',
    barLoading: 'Quelio…',
    barUnavailable: 'Quelio unavailable',
    barOffline: 'Offline',

    status_weekend: 'Weekend · {done} this week',
    status_weekendReached: 'Weekend · week done',
    status_dayOff: 'Day off',
    status_beforeArrival: 'Arrive from {time}',
    status_arrivalWindow: 'Arrive by {time}',
    status_noBadge: 'No badge today',
    status_dayDone: 'Day done · {paid}',
    status_away: 'Out since {time}',
    status_lunch: 'Lunch · {duration} of {minimum} · back at {time}',
    status_lunchDone: '{minimum} of lunch reached · free to go back',
    status_lunchEndSoon: 'Back before {by}',
    status_lunchLate: 'Lunch started after {start} · {duration} · back by {by}',
    status_lunchOverrun: 'Lunch running past {by}',
    status_pastLatest: 'Past the latest departure, {time}',
    status_lunchSoon: 'Lunch in {left}',
    status_lunchOpen: 'Lunch break available',
    status_lunchDeadline: 'Leave for lunch before {time}',
    status_lunchMissed: 'No lunch started before {time}',
    status_lunchBack: 'Lunch: {duration}',
    status_lunchShort: 'Lunch: {duration}, under {minimum}',
    status_weekReached: 'Week done · leave from {from}',
    status_weekReachedLeave: 'Week done · free to leave',
    status_insufficient: '{shortfall} short this week · stay until {time}',
    status_canLeave: 'Free to leave',
    status_dayReached: "Today's share done · leave from {from}",
    status_latestSoon: 'Leave by {time}',
    status_started: 'Arrived {arrival} · leave at {time}',
    status_working: '{left} to go · leave at {time}',

    updatedAt: 'Updated at {time}',
    updatedOn: 'Updated {day} at {time}',
    updating: 'Updating…',
    offlineSince: 'Offline · last read {time}',
    refresh: 'Refresh',
    refreshIn: 'Refresh possible in {left}',
    loading: 'Reading your hours…',

    sectionWeek: 'This week',
    rowDone: 'Done',
    rowObjective: 'Objective',
    rowRemaining: 'Remaining',
    rowProgress: 'Progress',
    objectiveHalfOff: '{target}, with an afternoon off',
    objectiveOneOff: '{target}, with one day off',
    objectiveManyOff: '{target}, with {count} days off',
    objectiveAssumed: '{target} (Quelio gave none)',
    insufficientDetail: 'Even leaving as late as allowed every day left, the week ends {shortfall} short.',
    reachedDetail: 'Objective reached. Leaving is allowed from {from}.',
    reachedDetailNow: 'Objective reached. Leaving is allowed now.',

    sectionToday: 'Today',
    rowArrival: 'Arrival',
    rowWorked: 'Counted',
    rowLunch: 'Lunch',
    rowLeft: 'Still to work',
    rowDeparture: 'Suggested departure',
    rowWindow: 'Allowed departure',
    rowDay: "Today's share",
    lunchNotYet: 'Not taken yet',
    lunchAfternoonOff: 'None: afternoon off',
    lunchOngoing: 'Since {from} · {duration}',
    lunchSpan: '{from}–{to} · {duration}',
    none: '—',

    sectionDays: 'Days',
    dayOff: 'Day off',
    dayOngoing: '{paid} so far',
    dayHalf: '{value} · afternoon off',
    markOff: 'Day off',
    unmarkOff: 'Not off',
    markOffHint: 'Counts this day as a fifth of the week',
    markHalf: 'Afternoon off',
    unmarkHalf: 'Whole day',
    markHalfHint: 'Counts this afternoon as a tenth of the week: no 16:30 floor, only the morning is planned',

    signOut: 'Sign out',
    settings: 'Settings',

    loginTitle: 'Sign in to Quelio',
    loginSubtitle: "Your working hours, in Slack's top bar.",
    fieldAddress: 'Quelio server address',
    fieldAddressHint: 'The quelio-api your company runs, ending in a slash.',
    fieldUser: 'Username',
    fieldPassword: 'Password',
    submit: 'Sign in',
    submitting: 'Signing in…',
    server: 'Server: {host}',
    privacy:
      'Your password is sent to {host} to sign in, and is not stored. The token Quelio answers with ' +
      'contains it, encrypted and hashed, so protect it like the password: it is kept, unencrypted, with ' +
      "this week's hours in ~/.betterslack/data/quelio/ on this computer. Signing out deletes it.",
    privacyNoHost:
      'Your password is sent to the address above to sign in, and is not stored. The token Quelio ' +
      'answers with contains it, encrypted and hashed, so protect it like the password: it is kept, ' +
      "unencrypted, with this week's hours in ~/.betterslack/data/quelio/ on this computer. Signing " +
      'out deletes it.',

    error_credentials: 'Quelio refused this username or password.',
    error_attemptsLeft: '{count} attempts left before Quelio blocks this network for a few minutes.',
    error_expired: 'Your Quelio session has ended. Sign in again.',
    error_rateLimited: 'Too many attempts: Quelio is waiting another {left}.',
    error_unreachable: 'Quelio cannot be reached.',
    error_timeout: 'Quelio took too long to answer.',
    error_address: 'This address cannot be used: it has to be https, and the one in the settings.',
    error_redirect: 'This address sends elsewhere. Check it in the settings.',
    error_notFound: 'Nothing answers at this address. Check it in the settings.',
    error_refused: 'Quelio refused the request.',
    error_server: 'Quelio ran into a problem.',
    error_malformed: "Quelio's answer could not be read.",
    error_empty: 'Fill in the username and the password.',
    error_busy: 'Already signing in.',
    retryAt: 'Next try at {time}.',

    signedIn: 'Signed in to Quelio',
    signedOut: 'Signed out of Quelio',
    expired: 'Quelio session expired',

    commandOpen: 'Quelio: my hours',
    commandRefresh: 'Quelio: refresh my hours',
  },
  fr: {
    title: 'Quelio',

    hours: '{h}h',
    hoursMinutes: '{h}h{mm}',
    minutes: '{m} min',
    percent: '{value} %',
    range: '{from}–{to}',
    until: 'jusqu’à {to}',
    weekTotal: '{done} / {target}',
    weekRemaining: '· reste {remaining}',
    barLabel: 'Quelio : {done} sur {target} cette semaine. {status}',

    barSignIn: 'Quelio · Se connecter',
    barSignInAgain: 'Quelio · Se reconnecter',
    barLoading: 'Quelio…',
    barUnavailable: 'Quelio indisponible',
    barOffline: 'Hors ligne',

    status_weekend: 'Week-end · {done} cette semaine',
    status_weekendReached: 'Week-end · semaine complète',
    status_dayOff: 'Congé',
    status_beforeArrival: 'Arrivée à partir de {time}',
    status_arrivalWindow: 'Arrivée avant {time}',
    status_noBadge: "Aucun badge aujourd'hui",
    status_dayDone: 'Journée terminée · {paid}',
    status_away: 'Sortie à {time}',
    status_lunch: 'Pause · {duration} / {minimum} · reprise à {time}',
    status_lunchDone: '{minimum} de pause atteinte · reprise possible',
    status_lunchEndSoon: 'Reprise nécessaire avant {by}',
    status_lunchLate: 'Pause commencée après {start} · {duration} · reprise avant {by}',
    status_lunchOverrun: 'Pause au-delà de {by}',
    status_pastLatest: 'Heure maximale dépassée, {time}',
    status_lunchSoon: 'Pause déjeuner dans {left}',
    status_lunchOpen: 'Pause déjeuner disponible',
    status_lunchDeadline: 'Départ en pause avant {time}',
    status_lunchMissed: 'Pas de pause commencée avant {time}',
    status_lunchBack: 'Pause : {duration}',
    status_lunchShort: 'Pause : {duration}, moins de {minimum}',
    status_weekReached: 'Semaine complète · départ dès {from}',
    status_weekReachedLeave: 'Semaine complète · départ possible',
    status_insufficient: 'Il manque {shortfall} · rester jusqu’à {time}',
    status_canLeave: 'Départ possible',
    status_dayReached: 'Objectif du jour atteint · départ dès {from}',
    status_latestSoon: 'Départ au plus tard à {time}',
    status_started: 'Arrivée {arrival} · départ {time}',
    status_working: 'Encore {left} · départ {time}',

    updatedAt: 'Mis à jour à {time}',
    updatedOn: 'Mis à jour {day} à {time}',
    updating: 'Mise à jour…',
    offlineSince: 'Hors ligne · dernière lecture à {time}',
    refresh: 'Actualiser',
    refreshIn: 'Actualisation possible dans {left}',
    loading: 'Lecture des heures…',

    sectionWeek: 'Cette semaine',
    rowDone: 'Effectué',
    rowObjective: 'Objectif',
    rowRemaining: 'Restant',
    rowProgress: 'Progression',
    objectiveHalfOff: '{target}, avec un après-midi de congé',
    objectiveOneOff: '{target}, avec un jour de congé',
    objectiveManyOff: '{target}, avec {count} jours de congé',
    objectiveAssumed: '{target} (non fourni par Quelio)',
    insufficientDetail:
      'Même en partant à l’heure maximale chaque jour restant, il manquera {shortfall} à la semaine.',
    reachedDetail: 'Objectif atteint. Départ autorisé dès {from}.',
    reachedDetailNow: 'Objectif atteint. Départ autorisé dès maintenant.',

    sectionToday: 'Aujourd’hui',
    rowArrival: 'Arrivée',
    rowWorked: 'Décompté',
    rowLunch: 'Pause déjeuner',
    rowLeft: 'Reste à faire',
    rowDeparture: 'Départ conseillé',
    rowWindow: 'Départ autorisé',
    rowDay: 'Journée',
    lunchNotYet: 'Pas encore prise',
    lunchAfternoonOff: 'Aucune : après-midi de congé',
    lunchOngoing: 'Depuis {from} · {duration}',
    lunchSpan: '{from}–{to} · {duration}',
    none: '—',

    sectionDays: 'Jours',
    dayOff: 'Congé',
    dayOngoing: '{paid} en cours',
    dayHalf: '{value} · après-midi de congé',
    markOff: 'Congé',
    unmarkOff: 'Pas en congé',
    markOffHint: 'Compte ce jour pour un cinquième de la semaine',
    markHalf: 'Après-midi',
    unmarkHalf: 'Journée entière',
    markHalfHint: 'Compte cet après-midi pour un dixième de la semaine : pas de départ minimum à 16:30, seule la matinée est prévue',

    signOut: 'Se déconnecter',
    settings: 'Réglages',

    loginTitle: 'Connexion à Quelio',
    loginSubtitle: 'Vos heures de travail, dans la barre du haut de Slack.',
    fieldAddress: 'Adresse du serveur Quelio',
    fieldAddressHint: 'Le quelio-api de votre entreprise, terminé par une barre oblique.',
    fieldUser: 'Identifiant',
    fieldPassword: 'Mot de passe',
    submit: 'Se connecter',
    submitting: 'Connexion…',
    server: 'Serveur : {host}',
    privacy:
      'Le mot de passe est envoyé à {host} pour la connexion, et n’est pas enregistré. Le jeton renvoyé ' +
      'par Quelio le contient, chiffré et haché : il est à protéger comme le mot de passe. Il est gardé, ' +
      'sans chiffrement, avec les heures de la semaine dans ~/.betterslack/data/quelio/ sur cet ' +
      'ordinateur. Se déconnecter l’efface.',
    privacyNoHost:
      'Le mot de passe est envoyé à l’adresse ci-dessus pour la connexion, et n’est pas enregistré. Le ' +
      'jeton renvoyé par Quelio le contient, chiffré et haché : il est à protéger comme le mot de ' +
      'passe. Il est gardé, sans chiffrement, avec les heures de la semaine dans ' +
      '~/.betterslack/data/quelio/ sur cet ordinateur. Se déconnecter l’efface.',

    error_credentials: 'Identifiant ou mot de passe refusé par Quelio.',
    error_attemptsLeft: 'Encore {count} essais avant que Quelio ne bloque ce réseau quelques minutes.',
    error_expired: 'La session Quelio a pris fin. Reconnexion nécessaire.',
    error_rateLimited: 'Trop de tentatives : Quelio attend encore {left}.',
    error_unreachable: 'Quelio est injoignable.',
    error_timeout: 'Quelio a mis trop de temps à répondre.',
    error_address: 'Adresse inutilisable : elle doit être en https, et être celle des réglages.',
    error_redirect: 'Cette adresse renvoie ailleurs. À vérifier dans les réglages.',
    error_notFound: 'Rien ne répond à cette adresse. À vérifier dans les réglages.',
    error_refused: 'Quelio a refusé la requête.',
    error_server: 'Quelio a rencontré un problème.',
    error_malformed: 'Réponse de Quelio illisible.',
    error_empty: 'Identifiant et mot de passe requis.',
    error_busy: 'Connexion déjà en cours.',
    retryAt: 'Nouvel essai à {time}.',

    signedIn: 'Connexion à Quelio réussie',
    signedOut: 'Déconnexion de Quelio effectuée',
    expired: 'Session Quelio expirée',

    commandOpen: 'Quelio : mes heures',
    commandRefresh: 'Quelio : actualiser mes heures',
  },
};
